Support all GitHub themes
sindresorhus/generate-github-markdown-css pull request #14
Opened 2022-07-14 20:13 UTC by ClementGaston

Hello,

I wanted to use your library, but it was missing a lot of GitHub theme. I decided to edit your work to support all current (and future) themes provided by GitHub (for the markdown). I let you see what I have done.

Here a snippet of my work: 
https://gyazo.com/556bb260ce12f954610a78365800bd11 

If you are happy of my work, I want to add next an option to output minified CSS :)

2022-07-21 15:50 UTC, sindresorhus commented on readme.md
> +	  light_colorblind
This is not part of the actual CLI output

2022-07-21 15:51 UTC, sindresorhus requested changes

2022-07-21 15:51 UTC, sindresorhus commented on test.js
> +				.then(css => {
Use Async/await.

2022-07-21 15:51 UTC, sindresorhus commented
I think `auto` should still be there for users that just want light/dark and auto-switching.

2022-07-21 15:52 UTC, sindresorhus commented
Nice work :)

2022-11-12 02:48 UTC, DarrenDanielDay commented
Looking forward to this feature for `dark dimmed` theme 👀

2022-12-08 19:42 UTC, closed without merging